extends Node

const POKEMONS = {
	"Bulbizarre": {
		"PV":45,
		"Attaque":49,
		"Defense":49,
		"AttaqueSpe":65,
		"DefenseSpe":65,
		"Vitesse":45,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":1}],
		"EXP":64,
		"Courbe_EXP":"Parabolique",
		"Poids":6.9,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Vampigraine","LvL":7},
			{"Attack":"Fouet Lianes","LvL":13},
			{"Attack":"Poudre Toxik","LvL":20},
			{"Attack":"Tranch'Herbe","LvL":27},
			{"Attack":"Croissance","LvL":34},
			{"Attack":"Poudre Dodo","LvL":41},
			{"Attack":"Lance-Soleil","LvL":48},
		],
		"Evolution":{"Name":"Herbizarre","LvL":16}},
	"Herbizarre": {
		"PV":60,
		"Attaque":62,
		"Defense":63,
		"AttaqueSpe":80,
		"DefenseSpe":80,
		"Vitesse":60,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":1},{"Stat":"DefenseSpe","Value":1}],
		"EXP":141,
		"Courbe_EXP":"Parabolique",
		"Poids":13,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Vampigraine","LvL":7},
			{"Attack":"Fouet Lianes","LvL":13},
			{"Attack":"Poudre Toxik","LvL":22},
			{"Attack":"Tranch'Herbe","LvL":30},
			{"Attack":"Croissance","LvL":38},
			{"Attack":"Poudre Dodo","LvL":46},
			{"Attack":"Lance-Soleil","LvL":54},
		],
		"Evolution":{"Name":"Florizarre","LvL":32}},
	"Florizarre": {
		"PV":80,
		"Attaque":82,
		"Defense":83,
		"AttaqueSpe":100,
		"DefenseSpe":100,
		"Vitesse":80,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":2},{"Stat":"DefenseSpe","Value":1}],
		"EXP":236,
		"Courbe_EXP":"Parabolique",
		"Poids":100,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Vampigraine","LvL":7},
			{"Attack":"Fouet Lianes","LvL":13},
			{"Attack":"Poudre Toxik","LvL":22},
			{"Attack":"Tranch'Herbe","LvL":30},
			{"Attack":"Croissance","LvL":43},
			{"Attack":"Poudre Dodo","LvL":55},
			{"Attack":"Lance-Soleil","LvL":65},
		],
		"Evolution":null},
	"Salamèche": {
		"PV":39,
		"Attaque":52,
		"Defense":43,
		"AttaqueSpe":60,
		"DefenseSpe":50,
		"Vitesse":65,
		"Type1":"Feu",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":65,
		"Courbe_EXP":"Parabolique",
		"Poids":8.5,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Flammèche","LvL":9},
			{"Attack":"Groz'Yeux","LvL":15},
			{"Attack":"Frénésie","LvL":22},
			{"Attack":"Tranche","LvL":30},
			{"Attack":"Lance-Flamme","LvL":38},
			{"Attack":"Danse-Flammes","LvL":46},
		],
		"Evolution":{"Name":"Reptincel","LvL":16}},
	"Reptincel": {
		"PV":58,
		"Attaque":64,
		"Defense":58,
		"AttaqueSpe":80,
		"DefenseSpe":65,
		"Vitesse":80,
		"Type1":"Feu",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1},{"Stat":"AttaqueSpe","Value":1}],
		"EXP":142,
		"Courbe_EXP":"Parabolique",
		"Poids":19,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Flammèche","LvL":9},
			{"Attack":"Groz'Yeux","LvL":15},
			{"Attack":"Frénésie","LvL":24},
			{"Attack":"Tranche","LvL":33},
			{"Attack":"Lance-Flamme","LvL":42},
			{"Attack":"Danse-Flammes","LvL":56},
		],
		"Evolution":{"Name":"Dracaufeu","LvL":36}},
	"Dracaufeu": {
		"PV":78,
		"Attaque":84,
		"Defense":78,
		"AttaqueSpe":109,
		"DefenseSpe":85,
		"Vitesse":100,
		"Type1":"Feu",
		"Type2":"Vol",
		"EV":[{"Stat":"AttaqueSpe","Value":3}],
		"EXP":209,
		"Courbe_EXP":"Parabolique",
		"Poids":90.5,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Flammèche","LvL":9},
			{"Attack":"Groz'Yeux","LvL":15},
			{"Attack":"Frénésie","LvL":24},
			{"Attack":"Tranche","LvL":36},
			{"Attack":"Lance-Flamme","LvL":46},
			{"Attack":"Danse-Flammes","LvL":55},
		],
		"Evolution":null},
	"Carapuce": {
		"PV":44,
		"Attaque":48,
		"Defense":65,
		"AttaqueSpe":50,
		"DefenseSpe":64,
		"Vitesse":43,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"Defense","Value":1}],
		"EXP":66,
		"Courbe_EXP":"Parabolique",
		"Poids":9,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Mimi-Queue","LvL":0},
			{"Attack":"Écume","LvL":8},
			{"Attack":"Pistolet à O","LvL":15},
			{"Attack":"Morsure","LvL":22},
			{"Attack":"Repli","LvL":28},
			{"Attack":"Coud'Krâne","LvL":35},
			{"Attack":"Hydrocanon","LvL":42},
		],
		"Evolution":{"Name":"Carabaffe","LvL":16}},
	"Carabaffe": {
		"PV":59,
		"Attaque":63,
		"Defense":80,
		"AttaqueSpe":65,
		"DefenseSpe":80,
		"Vitesse":58,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"Defense","Value":1},{"Stat":"DefenseSpe","Value":1}],
		"EXP":143,
		"Courbe_EXP":"Parabolique",
		"Poids":22.5,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Mimi-Queue","LvL":0},
			{"Attack":"Écume","LvL":8},
			{"Attack":"Pistolet à O","LvL":15},
			{"Attack":"Morsure","LvL":24},
			{"Attack":"Repli","LvL":31},
			{"Attack":"Coud'Krâne","LvL":39},
			{"Attack":"Hydrocanon","LvL":47},
		],
		"Evolution":{"Name":"Tortank","LvL":36}},
	"Tortank": {
		"PV":79,
		"Attaque":83,
		"Defense":100,
		"AttaqueSpe":85,
		"DefenseSpe":105,
		"Vitesse":78,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"DefenseSpe","Value":3}],
		"EXP":210,
		"Courbe_EXP":"Parabolique",
		"Poids":85.5,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Mimi-Queue","LvL":0},
			{"Attack":"Écume","LvL":8},
			{"Attack":"Pistolet à O","LvL":15},
			{"Attack":"Morsure","LvL":24},
			{"Attack":"Repli","LvL":31},
			{"Attack":"Coud'Krâne","LvL":42},
			{"Attack":"Hydrocanon","LvL":52},
		],
		"Evolution":null},
	"Chenipan": {
		"PV":45,
		"Attaque":30,
		"Defense":35,
		"AttaqueSpe":20,
		"DefenseSpe":20,
		"Vitesse":45,
		"Type1":"Insecte",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":1}],
		"EXP":53,
		"Courbe_EXP":"Moyenne",
		"Poids":2.9,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Sécrétion","LvL":0}
		],
		"Evolution":{"Name":"Chrysacier","LvL":7}},
	"Chrysacier": {
		"PV":50,
		"Attaque":20,
		"Defense":55,
		"AttaqueSpe":25,
		"DefenseSpe":25,
		"Vitesse":30,
		"Type1":"Insecte",
		"Type2":null,
		"EV":[{"Stat":"Defense","Value":2}],
		"EXP":72,
		"Courbe_EXP":"Moyenne",
		"Poids":9.9,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Armure","LvL":7}
		],
		"Evolution":{"Name":"Papilusion","LvL":10}},
	"Papilusion": {
		"PV":60,
		"Attaque":45,
		"Defense":50,
		"AttaqueSpe":90,
		"DefenseSpe":80,
		"Vitesse":70,
		"Type1":"Insecte",
		"Type2":"Vol",
		"EV":[{"Stat":"AttaqueSpe","Value":2},{"Stat":"DefenseSpe","Value":1}],
		"EXP":160,
		"Courbe_EXP":"Moyenne",
		"Poids":32,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Choc Mental","LvL":10},
			{"Attack":"Poudre Toxik","LvL":13},
			{"Attack":"Para-Spore","LvL":14},
			{"Attack":"Poudre Dodo","LvL":15},
			{"Attack":"Ultrason","LvL":18},
			{"Attack":"Cyclone","LvL":23},
			{"Attack":"Tornade","LvL":28},
			{"Attack":"Rafale Psy","LvL":34}
		],
		"Evolution":null},
	"Aspicot": {
		"PV":40,
		"Attaque":35,
		"Defense":30,
		"AttaqueSpe":20,
		"DefenseSpe":20,
		"Vitesse":50,
		"Type1":"Insecte",
		"Type2":"Poison",
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":52,
		"Courbe_EXP":"Moyenne",
		"Poids":3.2,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Dard-Venin","LvL":0},
			{"Attack":"Sécrétion","LvL":0},
		],
		"Evolution":{"Name":"Coconfort","LvL":7}},
	"Coconfort": {
		"PV":45,
		"Attaque":25,
		"Defense":50,
		"AttaqueSpe":25,
		"DefenseSpe":25,
		"Vitesse":35,
		"Type1":"Insecte",
		"Type2":"Poison",
		"EV":[{"Stat":"Defense","Value":2}],
		"EXP":71,
		"Courbe_EXP":"Moyenne",
		"Poids":10,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Armure","LvL":0},
		],
		"Evolution":{"Name":"Dardargnan","LvL":10}},
	"Dardargnan": {
		"PV":65,
		"Attaque":90,
		"Defense":40,
		"AttaqueSpe":45,
		"DefenseSpe":80,
		"Vitesse":75,
		"Type1":"Insecte",
		"Type2":"Poison",
		"EV":[{"Stat":"Attaque","Value":2},{"Stat":"DefenseSpe","Value":1}],
		"EXP":159,
		"Courbe_EXP":"Moyenne",
		"Poids":29.5,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Furie","LvL":12},
			{"Attack":"Puissance","LvL":16},
			{"Attack":"Double-Dard","LvL":20},
			{"Attack":"Frénésie","LvL":25},
			{"Attack":"Dard-Nuée","LvL":30},
			{"Attack":"Hâte","LvL":35}
		],
		"Evolution":null},
	"Roucool": {
		"PV":40,
		"Attaque":45,
		"Defense":40,
		"AttaqueSpe":35,
		"DefenseSpe":35,
		"Vitesse":56,
		"Type1":"Normal",
		"Type2":"Vol",
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":55,
		"Courbe_EXP":"Parabolique",
		"Poids":1.8,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Tornade","LvL":0},
			{"Attack":"Jet de Sable","LvL":5},
			{"Attack":"Vive-Attaque","LvL":12},
			{"Attack":"Cyclone","LvL":19},
			{"Attack":"Cru-Aile","LvL":28},
			{"Attack":"Hâte","LvL":36},
			{"Attack":"Mimique","LvL":44},
		],
		"Evolution":{"Name":"Roucoups","LvL":18}},
	"Roucoups": {
		"PV":63,
		"Attaque":60,
		"Defense":55,
		"AttaqueSpe":50,
		"DefenseSpe":50,
		"Vitesse":71,
		"Type1":"Normal",
		"Type2":"Vol",
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":113,
		"Courbe_EXP":"Parabolique",
		"Poids":30,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Tornade","LvL":0},
			{"Attack":"Jet de Sable","LvL":5},
			{"Attack":"Vive-Attaque","LvL":12},
			{"Attack":"Cyclone","LvL":19},
			{"Attack":"Cru-Aile","LvL":28},
			{"Attack":"Hâte","LvL":36},
			{"Attack":"Mimique","LvL":44},
		],
		"Evolution":{"Name":"Roucarnage","LvL":36}},
	"Roucarnage": {
		"PV":83,
		"Attaque":80,
		"Defense":75,
		"AttaqueSpe":70,
		"DefenseSpe":70,
		"Vitesse":101,
		"Type1":"Normal",
		"Type2":"Vol",
		"EV":[{"Stat":"Vitesse","Value":3}],
		"EXP":216,
		"Courbe_EXP":"Parabolique",
		"Poids":39.5,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Tornade","LvL":0},
			{"Attack":"Jet de Sable","LvL":5},
			{"Attack":"Vive-Attaque","LvL":12},
			{"Attack":"Cyclone","LvL":21},
			{"Attack":"Cru-Aile","LvL":31},
			{"Attack":"Hâte","LvL":44},
			{"Attack":"Mimique","LvL":54},
		],
		"Evolution":null},
	"Rattata": {
		"PV":30,
		"Attaque":56,
		"Defense":35,
		"AttaqueSpe":25,
		"DefenseSpe":35,
		"Vitesse":72,
		"Type1":"Normal",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":51,
		"Courbe_EXP":"Moyenne",
		"Poids":3.5,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Mimi-Queue","LvL":0},
			{"Attack":"Vive-Attaque","LvL":7},
			{"Attack":"Croc de Mort","LvL":14},
			{"Attack":"Puissance","LvL":23},
			{"Attack":"Croc Fatal","LvL":34},
		],
		"Evolution":{"Name":"Rattatac","LvL":20}},
	"Rattatac": {
		"PV":55,
		"Attaque":81,
		"Defense":60,
		"AttaqueSpe":50,
		"DefenseSpe":70,
		"Vitesse":97,
		"Type1":"Normal",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":116,
		"Courbe_EXP":"Moyenne",
		"Poids":18.5,
		"Taux_de_capture":127,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Mimi-Queue","LvL":0},
			{"Attack":"Vive-Attaque","LvL":7},
			{"Attack":"Croc de Mort","LvL":14},
			{"Attack":"Puissance","LvL":27},
			{"Attack":"Croc Fatal","LvL":41},
		],
		"Evolution":null},
	"Piafabec": {
		"PV":40,
		"Attaque":60,
		"Defense":30,
		"AttaqueSpe":31,
		"DefenseSpe":31,
		"Vitesse":70,
		"Type1":"Normal",
		"Type2":"Vol",
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":58,
		"Courbe_EXP":"Moyenne",
		"Poids":2,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Picpic","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Groz'Yeux","LvL":9},
			{"Attack":"Furie","LvL":15},
			{"Attack":"Mimique","LvL":22},
			{"Attack":"Bec Vrille","LvL":29},
			{"Attack":"Hâte","LvL":36}
		],
		"Evolution":{"Name":"Rapasdepic","LvL":20}},
	"Rapasdepic": {
		"PV":65,
		"Attaque":90,
		"Defense":65,
		"AttaqueSpe":61,
		"DefenseSpe":61,
		"Vitesse":100,
		"Type1":"Normal",
		"Type2":"Vol",
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":162,
		"Courbe_EXP":"Moyenne",
		"Poids":38,
		"Taux_de_capture":90,
		"NativeAttacks":[
			{"Attack":"Picpic","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Groz'Yeux","LvL":9},
			{"Attack":"Furie","LvL":15},
			{"Attack":"Mimique","LvL":25},
			{"Attack":"Bec Vrille","LvL":34},
			{"Attack":"Hâte","LvL":43}
		],
		"Evolution":null},
	"Abo": {
		"PV":35,
		"Attaque":60,
		"Defense":44,
		"AttaqueSpe":40,
		"DefenseSpe":54,
		"Vitesse":55,
		"Type1":"Poison",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":62,
		"Courbe_EXP":"Moyenne",
		"Poids":6.9,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Groz'Yeux","LvL":0},
			{"Attack":"Ligotage","LvL":0},
			{"Attack":"Dard-Venin","LvL":10},
			{"Attack":"Morsure","LvL":17},
			{"Attack":"Regard Médusant","LvL":24},
			{"Attack":"Grincement","LvL":31},
			{"Attack":"Acide","LvL":38}
		],
		"Evolution":{"Name":"Arbok","LvL":22}},
	"Arbok": {
		"PV":60,
		"Attaque":95,
		"Defense":69,
		"AttaqueSpe":65,
		"DefenseSpe":79,
		"Vitesse":80,
		"Type1":"Poison",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":2}],
		"EXP":147,
		"Courbe_EXP":"Moyenne",
		"Poids":65,
		"Taux_de_capture":90,
		"NativeAttacks":[
			{"Attack":"Groz'Yeux","LvL":0},
			{"Attack":"Ligotage","LvL":0},
			{"Attack":"Dard-Venin","LvL":10},
			{"Attack":"Morsure","LvL":17},
			{"Attack":"Regard Médusant","LvL":27},
			{"Attack":"Grincement","LvL":36},
			{"Attack":"Acide","LvL":47}
		],
		"Evolution":null},
	"Pikachu": {
		"PV":35,
		"Attaque":55,
		"Defense":40,
		"AttaqueSpe":50,
		"DefenseSpe":50,
		"Vitesse":90,
		"Type1":"Électrik",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":82,
		"Courbe_EXP":"Moyenne",
		"Poids":6,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Éclair","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Mimi-Queue","LvL":6},
			{"Attack":"Cage-Éclair","LvL":8},
			{"Attack":"Vive-Attaque","LvL":11},
			{"Attack":"Reflet","LvL":15},
			{"Attack":"Souplesse","LvL":20},
			{"Attack":"Météores","LvL":25},
			{"Attack":"Tonnerre","LvL":26},
			{"Attack":"Hâte","LvL":33},
			{"Attack":"Fatal-Foudre","LvL":41},
			{"Attack":"Mur Lumière","LvL":50},
		],
		"Evolution":{"Name":"Raichu","Objet":"Pierre Foudre"}},
	"Raichu": {
		"PV":60,
		"Attaque":90,
		"Defense":55,
		"AttaqueSpe":90,
		"DefenseSpe":80,
		"Vitesse":110,
		"Type1":"Électrik",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":3}],
		"EXP":122,
		"Courbe_EXP":"Moyenne",
		"Poids":30,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Éclair","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Cage-Éclair","LvL":0}
		],
		"Evolution":null},
	"Sabelette": {
		"PV":50,
		"Attaque":75,
		"Defense":85,
		"AttaqueSpe":20,
		"DefenseSpe":30,
		"Vitesse":40,
		"Type1":"Sol",
		"Type2":null,
		"EV":[{"Stat":"Defense","Value":1}],
		"EXP":93,
		"Courbe_EXP":"Moyenne",
		"Poids":12,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Jet de Sable","LvL":10},
			{"Attack":"Tranche","LvL":17},
			{"Attack":"Dard-Venin","LvL":24},
			{"Attack":"Météores","LvL":31},
			{"Attack":"Combo-Griffe","LvL":38}
		],
		"Evolution":{"Name":"Sablaireau","LvL":22}},
	"Sablaireau": {
		"PV":75,
		"Attaque":100,
		"Defense":110,
		"AttaqueSpe":45,
		"DefenseSpe":55,
		"Vitesse":65,
		"Type1":"Sol",
		"Type2":null,
		"EV":[{"Stat":"Defense","Value":2}],
		"EXP":163,
		"Courbe_EXP":"Moyenne",
		"Poids":29.5,
		"Taux_de_capture":90,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Jet de Sable","LvL":10},
			{"Attack":"Tranche","LvL":17},
			{"Attack":"Dard-Venin","LvL":27},
			{"Attack":"Météores","LvL":36},
			{"Attack":"Combo-Griffe","LvL":47}
		],
		"Evolution":null},
	"Nidoran♀": {
		"PV":55,
		"Attaque":47,
		"Defense":52,
		"AttaqueSpe":40,
		"DefenseSpe":40,
		"Vitesse":41,
		"Type1":"Poison",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":1}],
		"EXP":59,
		"Courbe_EXP":"Parabolique",
		"Poids":7,
		"Taux_de_capture":235,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Griffe","LvL":8},
			{"Attack":"Dard-Venin","LvL":14},
			{"Attack":"Mimi-Queue","LvL":21},
			{"Attack":"Morsure","LvL":29},
			{"Attack":"Combo-Griffe","LvL":36},
			{"Attack":"Double Pied","LvL":43}
		],
		"Evolution":{"Name":"Nidorina","LvL":16}},
	"Nidorina": {
		"PV":70,
		"Attaque":62,
		"Defense":67,
		"AttaqueSpe":55,
		"DefenseSpe":55,
		"Vitesse":56,
		"Type1":"Poison",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":2}],
		"EXP":117,
		"Courbe_EXP":"Parabolique",
		"Poids":20,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Griffe","LvL":8},
			{"Attack":"Dard-Venin","LvL":14},
			{"Attack":"Mimi-Queue","LvL":23},
			{"Attack":"Morsure","LvL":32},
			{"Attack":"Combo-Griffe","LvL":41},
			{"Attack":"Double Pied","LvL":50}
		],
		"Evolution":{"Name":"Nidoqueen","Objet":"Pierre Lune"}},
	"Nidoqueen": {
		"PV":70,
		"Attaque":62,
		"Defense":67,
		"AttaqueSpe":55,
		"DefenseSpe":55,
		"Vitesse":56,
		"Type1":"Poison",
		"Type2":"Sol",
		"EV":[{"Stat":"PV","Value":3}],
		"EXP":194,
		"Courbe_EXP":"Parabolique",
		"Poids":60,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Mimi-Queue","LvL":0},
			{"Attack":"Griffe","LvL":8},
			{"Attack":"Double Pied","LvL":12},
			{"Attack":"Dard-Venin","LvL":14},
			{"Attack":"Plaquage","LvL":23}
		],
		"Evolution":null},
	"Nidoran♂": {
		"PV":46,
		"Attaque":57,
		"Defense":40,
		"AttaqueSpe":40,
		"DefenseSpe":40,
		"Vitesse":50,
		"Type1":"Poison",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":60,
		"Courbe_EXP":"Parabolique",
		"Poids":9,
		"Taux_de_capture":235,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Groz'Yeux","LvL":0},
			{"Attack":"Koud'Korne","LvL":8},
			{"Attack":"Dard-Venin","LvL":14},
			{"Attack":"Puissance","LvL":21},
			{"Attack":"Furie","LvL":29},
			{"Attack":"Empal'Korne","LvL":36},
			{"Attack":"Double Pied","LvL":43}
		],
		"Evolution":{"Name":"Nidorino","LvL":16}},
	"Nidorino": {
		"PV":61,
		"Attaque":72,
		"Defense":57,
		"AttaqueSpe":55,
		"DefenseSpe":55,
		"Vitesse":65,
		"Type1":"Poison",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":2}],
		"EXP":118,
		"Courbe_EXP":"Parabolique",
		"Poids":19.5,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Groz'Yeux","LvL":0},
			{"Attack":"Koud'Korne","LvL":8},
			{"Attack":"Dard-Venin","LvL":14},
			{"Attack":"Puissance","LvL":23},
			{"Attack":"Furie","LvL":32},
			{"Attack":"Empal'Korne","LvL":41},
			{"Attack":"Double Pied","LvL":50}
		],
		"Evolution":{"Name":"Nidoking","Objet":"Pierre Lune"}},
	"Nidoking": {
		"PV":61,
		"Attaque":72,
		"Defense":57,
		"AttaqueSpe":55,
		"DefenseSpe":55,
		"Vitesse":65,
		"Type1":"Poison",
		"Type2":"Sol",
		"EV":[{"Stat":"Attaque","Value":3}],
		"EXP":195,
		"Courbe_EXP":"Parabolique",
		"Poids":62,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Koud'Korne","LvL":8},
			{"Attack":"Double Pied","LvL":12},
			{"Attack":"Dard-Venin","LvL":14},
			{"Attack":"Mania","LvL":23}
		],
		"Evolution":null},
	"Mélofée": {
		"PV":70,
		"Attaque":45,
		"Defense":48,
		"AttaqueSpe":60,
		"DefenseSpe":65,
		"Vitesse":35,
		"Type1":"Normal",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":2}],
		"EXP":68,
		"Courbe_EXP":"Rapide",
		"Poids":7.5,
		"Taux_de_capture":150,
		"NativeAttacks":[
			{"Attack":"Écras'Face","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Berceuse","LvL":13},
			{"Attack":"Torgnoles","LvL":18},
			{"Attack":"Lilliput","LvL":24},
			{"Attack":"Métronome","LvL":31},
			{"Attack":"Boul'Armure","LvL":39},
			{"Attack":"Mur Lumière","LvL":48}
		],
		"Evolution":{"Name":"Mélodeldfe","Objet":"Pierre Lune"}},
	"Mélodelfe": {
		"PV":95,
		"Attaque":70,
		"Defense":73,
		"AttaqueSpe":95,
		"DefenseSpe":90,
		"Vitesse":60,
		"Type1":"Normal",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":3}],
		"EXP":129,
		"Courbe_EXP":"Rapide",
		"Poids":40,
		"Taux_de_capture":25,
		"NativeAttacks":[
			{"Attack":"Berceuse","LvL":0},
			{"Attack":"Torgnoles","LvL":0},
			{"Attack":"Lilliput","LvL":0},
			{"Attack":"Métronome","LvL":0}
		],
		"Evolution":null},
	"Goupix": {
		"PV":38,
		"Attaque":41,
		"Defense":40,
		"AttaqueSpe":50,
		"DefenseSpe":65,
		"Vitesse":65,
		"Type1":"Feu",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":63,
		"Courbe_EXP":"Moyenne",
		"Poids":9.9,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Flammèce","LvL":0},
			{"Attack":"Mimi-Queue","LvL":0},
			{"Attack":"Vive-Attaque","LvL":16},
			{"Attack":"Hurlement","LvL":21},
			{"Attack":"Onde Folie","LvL":28},
			{"Attack":"Lance-Flammes","LvL":35},
			{"Attack":"Danse-Flammes","LvL":42}
		],
		"Evolution":{"Name":"Feunard","Objet":"Pierre Feu"}},
	"Feunard": {
		"PV":73,
		"Attaque":76,
		"Defense":75,
		"AttaqueSpe":81,
		"DefenseSpe":100,
		"Vitesse":100,
		"Type1":"Feu",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1},{"Stat":"DefenseSpe","Value":1}],
		"EXP":178,
		"Courbe_EXP":"Moyenne",
		"Poids":19.9,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Flammèce","LvL":0},
			{"Attack":"Mimi-Queue","LvL":0},
			{"Attack":"Vive-Attaque","LvL":0},
			{"Attack":"Hurlement","LvL":0}
		],
		"Evolution":null},
	"Rondoudou": {
		"PV":115,
		"Attaque":45,
		"Defense":20,
		"AttaqueSpe":45,
		"DefenseSpe":25,
		"Vitesse":20,
		"Type1":"Normal",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":2}],
		"EXP":76,
		"Courbe_EXP":"Rapide",
		"Poids":5.5,
		"Taux_de_capture":170,
		"NativeAttacks":[
			{"Attack":"Berceuse","LvL":0},
			{"Attack":"Écras'Face","LvL":9},
			{"Attack":"Entrave","LvL":14},
			{"Attack":"Boul'Armure","LvL":19},
			{"Attack":"Torgnoles","LvL":24},
			{"Attack":"Repos","LvL":29},
			{"Attack":"Plaquage","LvL":34},
			{"Attack":"Damoclès","LvL":39},
		],
		"Evolution":{"Name":"Grodoudou","Objet":"Pierre Lune"}},
	"Grodoudou": {
		"PV":140,
		"Attaque":70,
		"Defense":45,
		"AttaqueSpe":85,
		"DefenseSpe":50,
		"Vitesse":45,
		"Type1":"Normal",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":3}],
		"EXP":109,
		"Courbe_EXP":"Rapide",
		"Poids":12,
		"Taux_de_capture":50,
		"NativeAttacks":[
			{"Attack":"Berceuse","LvL":0},
			{"Attack":"Entrave","LvL":0},
			{"Attack":"Boul'Armure","LvL":0},
			{"Attack":"Torgnoles","LvL":0}
		],
		"Evolution":null},
	"Nosferapti": {
		"PV":40,
		"Attaque":45,
		"Defense":35,
		"AttaqueSpe":30,
		"DefenseSpe":40,
		"Vitesse":55,
		"Type1":"Poison",
		"Type2":"Vol",
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":54,
		"Courbe_EXP":"Moyenne",
		"Poids":7.5,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Vampirisme","LvL":0},
			{"Attack":"Ultrason","LvL":10},
			{"Attack":"Morsure","LvL":15},
			{"Attack":"Onde Folie","LvL":21},
			{"Attack":"Cru-Aile","LvL":28},
			{"Attack":"Buée Noire","LvL":36}
		],
		"Evolution":{"Name":"Nosferalto","LvL":22}},
	"Nosferalto": {
		"PV":75,
		"Attaque":80,
		"Defense":70,
		"AttaqueSpe":65,
		"DefenseSpe":75,
		"Vitesse":90,
		"Type1":"Poison",
		"Type2":"Vol",
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":171,
		"Courbe_EXP":"Moyenne",
		"Poids":55,
		"Taux_de_capture":90,
		"NativeAttacks":[
			{"Attack":"Vampirisme","LvL":0},
			{"Attack":"Ultrason","LvL":10},
			{"Attack":"Morsure","LvL":15},
			{"Attack":"Onde Folie","LvL":21},
			{"Attack":"Cru-Aile","LvL":28},
			{"Attack":"Buée Noire","LvL":36}
		],
		"Evolution":null},
	"Mystherbe": {
		"PV":45,
		"Attaque":50,
		"Defense":55,
		"AttaqueSpe":75,
		"DefenseSpe":65,
		"Vitesse":30,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":1}],
		"EXP":78,
		"Courbe_EXP":"Parabolique",
		"Poids":5.4,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Vol-Vie","LvL":0},
			{"Attack":"Poudre Toxik","LvL":15},
			{"Attack":"Para-Spore","LvL":17},
			{"Attack":"Poudre Dodo","LvL":19},
			{"Attack":"Acide","LvL":24},
			{"Attack":"Danse-Fleur","LvL":33},
			{"Attack":"Lance-Soleil","LvL":46}
		],
		"Evolution":{"Name":"Ortide","LvL":21}},
	"Ortide": {
		"PV":60,
		"Attaque":65,
		"Defense":70,
		"AttaqueSpe":85,
		"DefenseSpe":75,
		"Vitesse":40,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":2}],
		"EXP":132,
		"Courbe_EXP":"Parabolique",
		"Poids":8.6,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Vol-Vie","LvL":0},
			{"Attack":"Poudre Toxik","LvL":15},
			{"Attack":"Para-Spore","LvL":17},
			{"Attack":"Poudre Dodo","LvL":19},
			{"Attack":"Acide","LvL":28},
			{"Attack":"Danse-Fleur","LvL":38},
			{"Attack":"Lance-Soleil","LvL":52}
		],
		"Evolution":{"Name":"Rafflesia","Objet":"Pierre Plante"}},
	"Rafflesia": {
		"PV":75,
		"Attaque":80,
		"Defense":85,
		"AttaqueSpe":110,
		"DefenseSpe":90,
		"Vitesse":50,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":3}],
		"EXP":184,
		"Courbe_EXP":"Parabolique",
		"Poids":18.6,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Acide","LvL":0},
			{"Attack":"Danse-Fleur","LvL":0},
			{"Attack":"Poudre Toxik","LvL":15},
			{"Attack":"Para-Spore","LvL":17},
			{"Attack":"Poudre Dodo","LvL":19}
		],
		"Evolution":null},
	"Paras": {
		"PV":35,
		"Attaque":70,
		"Defense":55,
		"AttaqueSpe":45,
		"DefenseSpe":55,
		"Vitesse":25,
		"Type1":"Insecte",
		"Type2":"Plante",
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":70,
		"Courbe_EXP":"Parabolique",
		"Poids":5.4,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Para-Spore","LvL":13},
			{"Attack":"Vampirisme","LvL":20},
			{"Attack":"Spore","LvL":27},
			{"Attack":"Tranche","LvL":34},
			{"Attack":"Croissance","LvL":41}
		],
		"Evolution":{"Name":"Parasect","LvL":24}},
	"Parasect": {
		"PV":60,
		"Attaque":95,
		"Defense":80,
		"AttaqueSpe":60,
		"DefenseSpe":80,
		"Vitesse":30,
		"Type1":"Insecte",
		"Type2":"Plante",
		"EV":[{"Stat":"Attaque","Value":2},{"Stat":"Defense","Value":1}],
		"EXP":128,
		"Courbe_EXP":"Parabolique",
		"Poids":29.5,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Para-Spore","LvL":13},
			{"Attack":"Vampirisme","LvL":20},
			{"Attack":"Spore","LvL":30},
			{"Attack":"Tranche","LvL":39},
			{"Attack":"Croissance","LvL":48}
		],
		"Evolution":null},
	"Mimitoss": {
		"PV":60,
		"Attaque":55,
		"Defense":50,
		"AttaqueSpe":40,
		"DefenseSpe":55,
		"Vitesse":45,
		"Type1":"Insecte",
		"Type2":"Poison",
		"EV":[{"Stat":"DefenseSpe","Value":1}],
		"EXP":75,
		"Courbe_EXP":"Moyenne",
		"Poids":30,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Entrave","LvL":0},
			{"Attack":"Ultrason","LvL":11},
			{"Attack":"Choc Mental","LvL":19},
			{"Attack":"Poudre Toxik","LvL":22},
			{"Attack":"Vampirisme","LvL":27},
			{"Attack":"Para-Spore","LvL":30},
			{"Attack":"Rafale Psy","LvL":35},
			{"Attack":"Poudre Dodo","LvL":38},
			{"Attack":"Psyko","LvL":43},
		],
		"Evolution":{"Name":"Aéromite","LvL":31}},
	"Aéromite": {
		"PV":70,
		"Attaque":65,
		"Defense":60,
		"AttaqueSpe":90,
		"DefenseSpe":75,
		"Vitesse":90,
		"Type1":"Insecte",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":1},{"Stat":"Vitesse","Value":1}],
		"EXP":138,
		"Courbe_EXP":"Moyenne",
		"Poids":12.5,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Entrave","LvL":0},
			{"Attack":"Ultrason","LvL":0},
			{"Attack":"Choc Mental","LvL":0},
			{"Attack":"Poudre Toxik","LvL":22},
			{"Attack":"Vampirisme","LvL":27},
			{"Attack":"Para-Spore","LvL":30},
			{"Attack":"Rafale Psy","LvL":38},
			{"Attack":"Poudre Dodo","LvL":43},
			{"Attack":"Psyko","LvL":50},
		],
		"Evolution":null},
	"Taupiqueur": {
		"PV":10,
		"Attaque":55,
		"Defense":25,
		"AttaqueSpe":35,
		"DefenseSpe":45,
		"Vitesse":95,
		"Type1":"Sol",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":81,
		"Courbe_EXP":"Moyenne",
		"Poids":0.8,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Rugissement","LvL":15},
			{"Attack":"Tunnel","LvL":19},
			{"Attack":"Jet de Sable","LvL":24},
			{"Attack":"Tranche","LvL":31},
			{"Attack":"Séisme","LvL":40}
		],
		"Evolution":{"Name":"Triopiqueur","LvL":26}},
	"Triopiqueur": {
		"PV":35,
		"Attaque":100,
		"Defense":50,
		"AttaqueSpe":50,
		"DefenseSpe":70,
		"Vitesse":120,
		"Type1":"Sol",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":153,
		"Courbe_EXP":"Moyenne",
		"Poids":33.3,
		"Taux_de_capture":50,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Rugissement","LvL":15},
			{"Attack":"Tunnel","LvL":19},
			{"Attack":"Jet de Sable","LvL":24},
			{"Attack":"Tranche","LvL":31},
			{"Attack":"Séisme","LvL":40}
		],
		"Evolution":null},
	"Miaouss": {
		"PV":40,
		"Attaque":45,
		"Defense":35,
		"AttaqueSpe":40,
		"DefenseSpe":40,
		"Vitesse":90,
		"Type1":"Normal",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":69,
		"Courbe_EXP":"Moyenne",
		"Poids":4.2,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Morsure","LvL":12},
			{"Attack":"Jackpot","LvL":17},
			{"Attack":"Grincement","LvL":24},
			{"Attack":"Combo-Griffe","LvL":33},
			{"Attack":"Tranche","LvL":44}
		],
		"Evolution":{"Name":"Persian","LvL":28}},
	"Persian": {
		"PV":65,
		"Attaque":70,
		"Defense":60,
		"AttaqueSpe":65,
		"DefenseSpe":65,
		"Vitesse":115,
		"Type1":"Normal",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":148,
		"Courbe_EXP":"Moyenne",
		"Poids":32,
		"Taux_de_capture":90,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Rugissement","LvL":0},
			{"Attack":"Morsure","LvL":12},
			{"Attack":"Jackpot","LvL":17},
			{"Attack":"Grincement","LvL":24},
			{"Attack":"Combo-Griffe","LvL":33},
			{"Attack":"Tranche","LvL":44}
		],
		"Evolution": null},
	"Psykokwak": {
		"PV":50,
		"Attaque":52,
		"Defense":48,
		"AttaqueSpe":65,
		"DefenseSpe":50,
		"Vitesse":55,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"AttaqueSpe","Value":1}],
		"EXP":80,
		"Courbe_EXP":"Moyenne",
		"Poids":19.6,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Mimi-Queue","LvL":28},
			{"Attack":"Entrave","LvL":31},
			{"Attack":"Choc Mental","LvL":36},
			{"Attack":"Combo-Griffe","LvL":43},
			{"Attack":"Hydrocanon","LvL":52}
		],
		"Evolution": {"Name":"Akwakwak","LvL":33}},
	"Akwakwak": {
		"PV":80,
		"Attaque":82,
		"Defense":78,
		"AttaqueSpe":95,
		"DefenseSpe":80,
		"Vitesse":85,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"AttaqueSpe","Value":2}],
		"EXP":174,
		"Courbe_EXP":"Moyenne",
		"Poids":76.6,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Mimi-Queue","LvL":28},
			{"Attack":"Entrave","LvL":31},
			{"Attack":"Choc Mental","LvL":39},
			{"Attack":"Combo-Griffe","LvL":48},
			{"Attack":"Hydrocanon","LvL":59}
		],
		"Evolution": null},
	"Férosinge": {
		"PV":50,
		"Attaque":52,
		"Defense":48,
		"AttaqueSpe":65,
		"DefenseSpe":50,
		"Vitesse":55,
		"Type1":"Combat",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":74,
		"Courbe_EXP":"Moyenne",
		"Poids":28,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Groz'Yeux","LvL":0},
			{"Attack":"Balayage","LvL":9},
			{"Attack":"Poing-Karaté","LvL":15},
			{"Attack":"Combo-Griffe","LvL":21},
			{"Attack":"Puissance","LvL":27},
			{"Attack":"Frappe Atlas","LvL":33},
			{"Attack":"Mania","LvL":39},
			{"Attack":"Grincement","LvL":45},
		],
		"Evolution": {"Name":"Colossinge","LvL":28}},
	"Colossinge": {
		"PV":65,
		"Attaque":105,
		"Defense":60,
		"AttaqueSpe":60,
		"DefenseSpe":70,
		"Vitesse":95,
		"Type1":"Combat",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":2}],
		"EXP":149,
		"Courbe_EXP":"Moyenne",
		"Poids":32,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Griffe","LvL":0},
			{"Attack":"Groz'Yeux","LvL":0},
			{"Attack":"Balayage","LvL":9},
			{"Attack":"Poing-Karaté","LvL":15},
			{"Attack":"Combo-Griffe","LvL":21},
			{"Attack":"Puissance","LvL":27},
			{"Attack":"Frénésie","LvL":28},
			{"Attack":"Frappe Atlas","LvL":37},
			{"Attack":"Grincement","LvL":45},
			{"Attack":"Mania","LvL":46},
		],
		"Evolution": null},
	"Caninos": {
		"PV":50,
		"Attaque":52,
		"Defense":48,
		"AttaqueSpe":65,
		"DefenseSpe":50,
		"Vitesse":55,
		"Type1":"Feu",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":91,
		"Courbe_EXP":"Lente",
		"Poids":19,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Hurlement","LvL":0},
			{"Attack":"Morsure","LvL":0},
			{"Attack":"Flammèche","LvL":18},
			{"Attack":"Groz'Yeux","LvL":23},
			{"Attack":"Bélier","LvL":30},
			{"Attack":"Hâte","LvL":39},
			{"Attack":"Lance-Flammes","LvL":50}
		],
		"Evolution": {"Name":"Arcanin","Objet":"Pierre Feu"}},
	"Arcanin": {
		"PV":90,
		"Attaque":110,
		"Defense":80,
		"AttaqueSpe":100,
		"DefenseSpe":80,
		"Vitesse":95,
		"Type1":"Feu",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":2}],
		"EXP":213,
		"Courbe_EXP":"Lente",
		"Poids":155,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Hurlement","LvL":0},
			{"Attack":"Flammèche","LvL":0},
			{"Attack":"Groz'Yeux","LvL":0},
			{"Attack":"Bélier","LvL":0},
		],
		"Evolution": null},
	"Ptitard": {
		"PV":40,
		"Attaque":50,
		"Defense":40,
		"AttaqueSpe":40,
		"DefenseSpe":40,
		"Vitesse":90,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":77,
		"Courbe_EXP":"Parabolique",
		"Poids":12.4,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Écume","LvL":0},
			{"Attack":"Hypnose","LvL":16},
			{"Attack":"Pistolet à O","LvL":19},
			{"Attack":"Torgnoles","LvL":25},
			{"Attack":"Plaquage","LvL":31},
			{"Attack":"Amnésie","LvL":38},
			{"Attack":"Hydrocanon","LvL":45}
		],
		"Evolution": {"Name":"Têtarte","LvL":25}},
	"Têtarte": {
		"PV":65,
		"Attaque":65,
		"Defense":65,
		"AttaqueSpe":50,
		"DefenseSpe":50,
		"Vitesse":90,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":131,
		"Courbe_EXP":"Parabolique",
		"Poids":20,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Écume","LvL":0},
			{"Attack":"Hypnose","LvL":16},
			{"Attack":"Pistolet à O","LvL":19},
			{"Attack":"Torgnoles","LvL":26},
			{"Attack":"Plaquage","LvL":33},
			{"Attack":"Amnésie","LvL":41},
			{"Attack":"Hydrocanon","LvL":49}
		],
		"Evolution": {"Name":"Tartard","Objet":"Pierre Eau"}},
	"Tartard": {
		"PV":90,
		"Attaque":95,
		"Defense":95,
		"AttaqueSpe":70,
		"DefenseSpe":90,
		"Vitesse":70,
		"Type1":"Eau",
		"Type2":"Combat",
		"EV":[{"Stat":"Défense","Value":3}],
		"EXP":185,
		"Courbe_EXP":"Parabolique",
		"Poids":54,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Torgnoles","LvL":0},
			{"Attack":"Plaquage","LvL":0},
			{"Attack":"Hypnose","LvL":16},
			{"Attack":"Pistolet à O","LvL":19}
		],
		"Evolution": null},
	"Abra": {
		"PV":25,
		"Attaque":20,
		"Defense":15,
		"AttaqueSpe":105,
		"DefenseSpe":55,
		"Vitesse":90,
		"Type1":"Psy",
		"Type2":null,
		"EV":[{"Stat":"AttaqueSpe","Value":1}],
		"EXP":75,
		"Courbe_EXP":"Parabolique",
		"Poids":19.5,
		"Taux_de_capture":200,
		"NativeAttacks":[
			{"Attack":"Téléport","LvL":0}
		],
		"Evolution": {"Name":"Kadabra","LvL":16}},
	"Kadabra": {
		"PV":40,
		"Attaque":35,
		"Defense":30,
		"AttaqueSpe":120,
		"DefenseSpe":70,
		"Vitesse":105,
		"Type1":"Psy",
		"Type2":null,
		"EV":[{"Stat":"AttaqueSpe","Value":2}],
		"EXP":145,
		"Courbe_EXP":"Parabolique",
		"Poids":56.5,
		"Taux_de_capture":100,
		"NativeAttacks":[
			{"Attack":"Télékinésie","LvL":0},
			{"Attack":"Téléport","LvL":0},
			{"Attack":"Choc Mental","LvL":16},
			{"Attack":"Entrave","LvL":20},
			{"Attack":"Rafale Psy","LvL":27},
			{"Attack":"Soin","LvL":31},
			{"Attack":"Psyko","LvL":38},
			{"Attack":"Protection","LvL":42},
		],
		"Evolution": {"Name":"Kadabra","Autre":"Échange"}},
	"Alakazam": {
		"PV":55,
		"Attaque":50,
		"Defense":45,
		"AttaqueSpe":135,
		"DefenseSpe":95,
		"Vitesse":120,
		"Type1":"Psy",
		"Type2":null,
		"EV":[{"Stat":"AttaqueSpe","Value":3}],
		"EXP":186,
		"Courbe_EXP":"Parabolique",
		"Poids":48,
		"Taux_de_capture":50,
		"NativeAttacks":[
			{"Attack":"Télékinésie","LvL":0},
			{"Attack":"Téléport","LvL":0},
			{"Attack":"Choc Mental","LvL":16},
			{"Attack":"Entrave","LvL":20},
			{"Attack":"Rafale Psy","LvL":27},
			{"Attack":"Soin","LvL":31},
			{"Attack":"Psyko","LvL":38},
			{"Attack":"Protection","LvL":42},
		],
		"Evolution": null},
	"Machoc": {
		"PV":70,
		"Attaque":80,
		"Defense":50,
		"AttaqueSpe":35,
		"DefenseSpe":35,
		"Vitesse":35,
		"Type1":"Combat",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":75,
		"Courbe_EXP":"Parabolique",
		"Poids":19.5,
		"Taux_de_capture":180,
		"NativeAttacks":[
			{"Attack":"Poing-Karaté","LvL":0},
			{"Attack":"Balayage","LvL":20},
			{"Attack":"Groz'Yeux","LvL":25},
			{"Attack":"Puissance","LvL":32},
			{"Attack":"Frappe Atlas","LvL":39},
			{"Attack":"Sacrifice","LvL":46}
		],
		"Evolution": {"Name":"Machopeur","LvL":28}},
	"Machopeur": {
		"PV":80,
		"Attaque":100,
		"Defense":70,
		"AttaqueSpe":50,
		"DefenseSpe":60,
		"Vitesse":45,
		"Type1":"Combat",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":2}],
		"EXP":146,
		"Courbe_EXP":"Parabolique",
		"Poids":70.5,
		"Taux_de_capture":90,
		"NativeAttacks":[
			{"Attack":"Poing-Karaté","LvL":0},
			{"Attack":"Balayage","LvL":20},
			{"Attack":"Groz'Yeux","LvL":25},
			{"Attack":"Puissance","LvL":36},
			{"Attack":"Frappe Atlas","LvL":44},
			{"Attack":"Sacrifice","LvL":52}
		],
		"Evolution": {"Name":"Mackogneur","Autre":"Échange"}},
	"Mackogneur": {
		"PV":90,
		"Attaque":130,
		"Defense":80,
		"AttaqueSpe":65,
		"DefenseSpe":85,
		"Vitesse":55,
		"Type1":"Combat",
		"Type2":null,
		"EV":[{"Stat":"Attaque","Value":3}],
		"EXP":193,
		"Courbe_EXP":"Parabolique",
		"Poids":130,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Poing-Karaté","LvL":0},
			{"Attack":"Balayage","LvL":20},
			{"Attack":"Groz'Yeux","LvL":25},
			{"Attack":"Puissance","LvL":36},
			{"Attack":"Frappe Atlas","LvL":44},
			{"Attack":"Sacrifice","LvL":52}
		],
		"Evolution": null},
	"Chétiflor": {
		"PV":50,
		"Attaque":75,
		"Defense":35,
		"AttaqueSpe":70,
		"DefenseSpe":30,
		"Vitesse":40,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":84,
		"Courbe_EXP":"Parabolique",
		"Poids":4,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Croissance","LvL":0},
			{"Attack":"Fouet Lianes","LvL":0},
			{"Attack":"Ligotage","LvL":13},
			{"Attack":"Poudre Toxik","LvL":15},
			{"Attack":"Poudre Dodo","LvL":18},
			{"Attack":"Para-Spore","LvL":21},
			{"Attack":"Acide","LvL":26},
			{"Attack":"Tranch'Herbe","LvL":33},
			{"Attack":"Souplesse","LvL":42}
		],
		"Evolution": {"Name":"Boustiflor","LvL":21}},
	"Boustiflor": {
		"PV":65,
		"Attaque":90,
		"Defense":50,
		"AttaqueSpe":85,
		"DefenseSpe":45,
		"Vitesse":55,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"Attaque","Value":2}],
		"EXP":151,
		"Courbe_EXP":"Parabolique",
		"Poids":6.4,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Croissance","LvL":0},
			{"Attack":"Fouet Lianes","LvL":0},
			{"Attack":"Ligotage","LvL":13},
			{"Attack":"Poudre Toxik","LvL":15},
			{"Attack":"Poudre Dodo","LvL":18},
			{"Attack":"Para-Spore","LvL":23},
			{"Attack":"Acide","LvL":29},
			{"Attack":"Tranch'Herbe","LvL":38},
			{"Attack":"Souplesse","LvL":49}
		],
		"Evolution": {"Name":"Empliflor","Objet":"Pierre Plante"}},
	"Empliflor": {
		"PV":80,
		"Attaque":105,
		"Defense":65,
		"AttaqueSpe":100,
		"DefenseSpe":70,
		"Vitesse":70,
		"Type1":"Plante",
		"Type2":"Poison",
		"EV":[{"Stat":"Attaque","Value":3}],
		"EXP":191,
		"Courbe_EXP":"Parabolique",
		"Poids":15.5,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Para-Spore","LvL":0},
			{"Attack":"Acide","LvL":0},
			{"Attack":"Tranch'Herbe","LvL":0},
			{"Attack":"Ligotage","LvL":13},
			{"Attack":"Poudre Toxik","LvL":15},
			{"Attack":"Poudre Dodo","LvL":18},
		],
		"Evolution": null},
	"Tentacool": {
		"PV":40,
		"Attaque":40,
		"Defense":35,
		"AttaqueSpe":50,
		"DefenseSpe":100,
		"Vitesse":70,
		"Type1":"Eau",
		"Type2":"Poison",
		"EV":[{"Stat":"DefenseSpe","Value":1}],
		"EXP":105,
		"Courbe_EXP":"Lente",
		"Poids":45.5,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Acide","LvL":0},
			{"Attack":"Ultrason","LvL":7},
			{"Attack":"Ligotage","LvL":13},
			{"Attack":"Dard-Venin","LvL":18},
			{"Attack":"Pistolet à O","LvL":22},
			{"Attack":"Constriction","LvL":27},
			{"Attack":"Bouclier","LvL":33},
			{"Attack":"Grincement","LvL":40},
			{"Attack":"Hydrocanon","LvL":48}
		],
		"Evolution": {"Name":"Tentacruel","LvL":30}},
	"Tentacruel": {
		"PV":80,
		"Attaque":70,
		"Defense":65,
		"AttaqueSpe":80,
		"DefenseSpe":120,
		"Vitesse":100,
		"Type1":"Eau",
		"Type2":"Poison",
		"EV":[{"Stat":"DefenseSpe","Value":2}],
		"EXP":205,
		"Courbe_EXP":"Lente",
		"Poids":55,
		"Taux_de_capture":60,
		"NativeAttacks":[
			{"Attack":"Acide","LvL":0},
			{"Attack":"Ultrason","LvL":7},
			{"Attack":"Ligotage","LvL":13},
			{"Attack":"Dard-Venin","LvL":18},
			{"Attack":"Pistolet à O","LvL":22},
			{"Attack":"Constriction","LvL":27},
			{"Attack":"Bouclier","LvL":35},
			{"Attack":"Grincement","LvL":43},
			{"Attack":"Hydrocanon","LvL":50}
		],
		"Evolution": null},
	"Racaillou": {
		"PV":40,
		"Attaque":80,
		"Defense":100,
		"AttaqueSpe":30,
		"DefenseSpe":30,
		"Vitesse":20,
		"Type1":"Roche",
		"Type2":"Sol",
		"EV":[{"Stat":"Defense","Value":1}],
		"EXP":73,
		"Courbe_EXP":"Parabolique",
		"Poids":20,
		"Taux_de_capture":255,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Boul'Armure","LvL":11},
			{"Attack":"Jet-Pierres","LvL":16},
			{"Attack":"Destruction","LvL":21},
			{"Attack":"Armure","LvL":26},
			{"Attack":"Séisme","LvL":31},
			{"Attack":"Explosion","LvL":36},
		],
		"Evolution": {"Name":"Gravalanch","LvL":25}},
	"Gravalanch": {
		"PV":55,
		"Attaque":95,
		"Defense":115,
		"AttaqueSpe":45,
		"DefenseSpe":45,
		"Vitesse":35,
		"Type1":"Roche",
		"Type2":"Sol",
		"EV":[{"Stat":"Defense","Value":2}],
		"EXP":134,
		"Courbe_EXP":"Parabolique",
		"Poids":105,
		"Taux_de_capture":120,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Boul'Armure","LvL":11},
			{"Attack":"Jet-Pierres","LvL":16},
			{"Attack":"Destruction","LvL":21},
			{"Attack":"Armure","LvL":29},
			{"Attack":"Séisme","LvL":36},
			{"Attack":"Explosion","LvL":43},
		],
		"Evolution": {"Name":"Grolem","Autre":"Échange"}},
	"Grolem": {
		"PV":80,
		"Attaque":120,
		"Defense":130,
		"AttaqueSpe":55,
		"DefenseSpe":65,
		"Vitesse":45,
		"Type1":"Roche",
		"Type2":"Sol",
		"EV":[{"Stat":"Defense","Value":3}],
		"EXP":177,
		"Courbe_EXP":"Parabolique",
		"Poids":300,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Boul'Armure","LvL":11},
			{"Attack":"Jet-Pierres","LvL":16},
			{"Attack":"Destruction","LvL":21},
			{"Attack":"Armure","LvL":29},
			{"Attack":"Séisme","LvL":36},
			{"Attack":"Explosion","LvL":43},
		],
		"Evolution": null},
	"Ponyta": {
		"PV":50,
		"Attaque":85,
		"Defense":55,
		"AttaqueSpe":65,
		"DefenseSpe":65,
		"Vitesse":90,
		"Type1":"Feu",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":1}],
		"EXP":82,
		"Courbe_EXP":"Moyenne",
		"Poids":30,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Flammèche","LvL":0},
			{"Attack":"Mimi-Queue","LvL":30},
			{"Attack":"Écrasement","LvL":32},
			{"Attack":"Rugissement","LvL":35},
			{"Attack":"Danse-Flammes","LvL":39},
			{"Attack":"Bélier","LvL":43},
			{"Attack":"Hâte","LvL":48},
		],
		"Evolution": {"Name":"Galopa","LvL":40}},
	"Galopa": {
		"PV":65,
		"Attaque":100,
		"Defense":70,
		"AttaqueSpe":80,
		"DefenseSpe":80,
		"Vitesse":105,
		"Type1":"Feu",
		"Type2":null,
		"EV":[{"Stat":"Vitesse","Value":2}],
		"EXP":192,
		"Courbe_EXP":"Moyenne",
		"Poids":95,
		"Taux_de_capture":60,
		"NativeAttacks":[
			{"Attack":"Flammèche","LvL":0},
			{"Attack":"Mimi-Queue","LvL":30},
			{"Attack":"Écrasement","LvL":32},
			{"Attack":"Rugissement","LvL":35},
			{"Attack":"Danse-Flammes","LvL":39},
			{"Attack":"Bélier","LvL":47},
			{"Attack":"Hâte","LvL":55},
		],
		"Evolution": null},
	"Ramoloss": {
		"PV":90,
		"Attaque":65,
		"Defense":65,
		"AttaqueSpe":40,
		"DefenseSpe":40,
		"Vitesse":15,
		"Type1":"Eau",
		"Type2":"Psy",
		"EV":[{"Stat":"PV","Value":1}],
		"EXP":99,
		"Courbe_EXP":"Moyenne",
		"Poids":36,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Choc Mental","LvL":0},
			{"Attack":"Entrave","LvL":18},
			{"Attack":"Coup d'Boule","LvL":22},
			{"Attack":"Rugissement","LvL":27},
			{"Attack":"Pistolet à O","LvL":33},
			{"Attack":"Amnésie","LvL":40},
			{"Attack":"Psyko","LvL":48}
		],
		"Evolution": {"Name":"Flagadoss","LvL":37}},
	"Flagadoss": {
		"PV":95,
		"Attaque":75,
		"Defense":110,
		"AttaqueSpe":100,
		"DefenseSpe":80,
		"Vitesse":30,
		"Type1":"Eau",
		"Type2":"Psy",
		"EV":[{"Stat":"Defense","Value":2}],
		"EXP":164,
		"Courbe_EXP":"Moyenne",
		"Poids":78.5,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Choc Mental","LvL":0},
			{"Attack":"Entrave","LvL":18},
			{"Attack":"Coup d'Boule","LvL":22},
			{"Attack":"Rugissement","LvL":27},
			{"Attack":"Pistolet à O","LvL":33},
			{"Attack":"Repli","LvL":37},
			{"Attack":"Amnésie","LvL":44},
			{"Attack":"Psyko","LvL":55}
		],
		"Evolution": null},
	"Magnéti": {
		"PV":25,
		"Attaque":35,
		"Defense":70,
		"AttaqueSpe":95,
		"DefenseSpe":55,
		"Vitesse":45,
		"Type1":"Électrik",
		"Type2":null,
		"EV":[{"Stat":"AttaqueSpe","Value":1}],
		"EXP":89,
		"Courbe_EXP":"Moyenne",
		"Poids":6,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Sonicboom","LvL":21},
			{"Attack":"Éclair","LvL":25},
			{"Attack":"Ultrason","LvL":29},
			{"Attack":"Cage-Éclair","LvL":35},
			{"Attack":"Météores","LvL":41},
			{"Attack":"Grincement","LvL":47}
		],
		"Evolution": {"Name":"Magnéton","LvL":30}},
	"Magnéton": {
		"PV":50,
		"Attaque":60,
		"Defense":95,
		"AttaqueSpe":120,
		"DefenseSpe":70,
		"Vitesse":70,
		"Type1":"Électrik",
		"Type2":null,
		"EV":[{"Stat":"AttaqueSpe","Value":2}],
		"EXP":161,
		"Courbe_EXP":"Moyenne",
		"Poids":60,
		"Taux_de_capture":60,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Sonicboom","LvL":21},
			{"Attack":"Éclair","LvL":25},
			{"Attack":"Ultrason","LvL":29},
			{"Attack":"Cage-Éclair","LvL":38},
			{"Attack":"Météores","LvL":46},
			{"Attack":"Grincement","LvL":54}
		],
		"Evolution": null},
	"Canarticho": {
		"PV":52,
		"Attaque":90,
		"Defense":55,
		"AttaqueSpe":58,
		"DefenseSpe":62,
		"Vitesse":60,
		"Type1":"Normal",
		"Type2":"Vol",
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":94,
		"Courbe_EXP":"Moyenne",
		"Poids":15,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Jet de Sable","LvL":0},
			{"Attack":"Picpic","LvL":0},
			{"Attack":"Groz'Yeux","LvL":7},
			{"Attack":"Furie","LvL":15},
			{"Attack":"Danse-Lames","LvL":23},
			{"Attack":"Hâte","LvL":31},
			{"Attack":"Tranche","LvL":39}
		],
		"Evolution": null},
	"Doduo": {
		"PV":35,
		"Attaque":85,
		"Defense":45,
		"AttaqueSpe":35,
		"DefenseSpe":35,
		"Vitesse":75,
		"Type1":"Normal",
		"Type2":"Vol",
		"EV":[{"Stat":"Attaque","Value":1}],
		"EXP":96,
		"Courbe_EXP":"Moyenne",
		"Poids":39.2,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Picpic","LvL":0},
			{"Attack":"Rugissement","LvL":20},
			{"Attack":"Furie","LvL":24},
			{"Attack":"Bec Vrille","LvL":30},
			{"Attack":"Frénésie","LvL":36},
			{"Attack":"Triplattaque","LvL":40},
			{"Attack":"Hâte","LvL":44}
		],
		"Evolution": {"Name":"Dodrio","LvL":31}},
	"Dodrio": {
		"PV":60,
		"Attaque":110,
		"Defense":70,
		"AttaqueSpe":60,
		"DefenseSpe":60,
		"Vitesse":110,
		"Type1":"Normal",
		"Type2":"Vol",
		"EV":[{"Stat":"Attaque","Value":2}],
		"EXP":158,
		"Courbe_EXP":"Moyenne",
		"Poids":85.2,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Picpic","LvL":0},
			{"Attack":"Rugissement","LvL":20},
			{"Attack":"Furie","LvL":24},
			{"Attack":"Bec Vrille","LvL":30},
			{"Attack":"Frénésie","LvL":39},
			{"Attack":"Triplattaque","LvL":45},
			{"Attack":"Hâte","LvL":51}
		],
		"Evolution": null},
	"Otaria": {
		"PV":65,
		"Attaque":45,
		"Defense":55,
		"AttaqueSpe":45,
		"DefenseSpe":70,
		"Vitesse":45,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"DefenseSpe","Value":1}],
		"EXP":100,
		"Courbe_EXP":"Moyenne",
		"Poids":90,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Coup d'Boule","LvL":0},
			{"Attack":"Rugissement","LvL":30},
			{"Attack":"Onde Boréale","LvL":35},
			{"Attack":"Repos","LvL":40},
			{"Attack":"Bélier","LvL":45},
			{"Attack":"Laser Glace","LvL":50}
		],
		"Evolution": {"Name":"Lamantine","LvL":34}},
	"Lamantine": {
		"PV":90,
		"Attaque":70,
		"Defense":80,
		"AttaqueSpe":70,
		"DefenseSpe":95,
		"Vitesse":70,
		"Type1":"Eau",
		"Type2":"Glace",
		"EV":[{"Stat":"DefenseSpe","Value":2}],
		"EXP":176,
		"Courbe_EXP":"Moyenne",
		"Poids":120,
		"Taux_de_capture":75,
		"NativeAttacks":[
			{"Attack":"Coup d'Boule","LvL":0},
			{"Attack":"Rugissement","LvL":30},
			{"Attack":"Onde Boréale","LvL":35},
			{"Attack":"Repos","LvL":44},
			{"Attack":"Bélier","LvL":50},
			{"Attack":"Laser Glace","LvL":56}
		],
		"Evolution": null},
	"Tadmorv": {
		"PV":80,
		"Attaque":80,
		"Defense":50,
		"AttaqueSpe":40,
		"DefenseSpe":50,
		"Vitesse":25,
		"Type1":"Poison",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":1}],
		"EXP":90,
		"Courbe_EXP":"Moyenne",
		"Poids":30,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Écras'Face","LvL":0},
			{"Attack":"Entrave","LvL":0},
			{"Attack":"Gaz Toxik","LvL":30},
			{"Attack":"Lilliput","LvL":33},
			{"Attack":"Détritus","LvL":37},
			{"Attack":"Armure","LvL":42},
			{"Attack":"Grincement","LvL":48},
			{"Attack":"Acidarmure","LvL":55},
		],
		"Evolution": {"Name":"Grotadmorv","LvL":38}},
	"Grotadmorv": {
		"PV":105,
		"Attaque":105,
		"Defense":75,
		"AttaqueSpe":65,
		"DefenseSpe":100,
		"Vitesse":50,
		"Type1":"Poison",
		"Type2":null,
		"EV":[{"Stat":"PV","Value":1},{"Stat":"Attaque","Value":1}],
		"EXP":157,
		"Courbe_EXP":"Moyenne",
		"Poids":30,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Écras'Face","LvL":0},
			{"Attack":"Entrave","LvL":0},
			{"Attack":"Gaz Toxik","LvL":30},
			{"Attack":"Lilliput","LvL":33},
			{"Attack":"Détritus","LvL":37},
			{"Attack":"Armure","LvL":45},
			{"Attack":"Grincement","LvL":53},
			{"Attack":"Acidarmure","LvL":60},
		],
		"Evolution": null},
	"Kokiyas": {
		"PV":30,
		"Attaque":65,
		"Defense":100,
		"AttaqueSpe":45,
		"DefenseSpe":25,
		"Vitesse":40,
		"Type1":"Eau",
		"Type2":null,
		"EV":[{"Stat":"Defense","Value":1}],
		"EXP":97,
		"Courbe_EXP":"Parabolique",
		"Poids":4,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Repli","LvL":0},
			{"Attack":"Ultrason","LvL":18},
			{"Attack":"Claquoir","LvL":23},
			{"Attack":"Onde Boréale","LvL":30},
			{"Attack":"Groz'Yeuxs","LvL":39},
			{"Attack":"Laser Glace","LvL":50}
		],
		"Evolution": {"Name":"Crustabri","Objet":"Pierre Eau"}},
	"Crustabri": {
		"PV":50,
		"Attaque":95,
		"Defense":180,
		"AttaqueSpe":85,
		"DefenseSpe":45,
		"Vitesse":70,
		"Type1":"Eau",
		"Type2":"Glace",
		"EV":[{"Stat":"Defense","Value":2}],
		"EXP":203,
		"Courbe_EXP":"Parabolique",
		"Poids":132.5,
		"Taux_de_capture":60,
		"NativeAttacks":[
			{"Attack":"Claquoir","LvL":0},
			{"Attack":"Repli","LvL":0},
			{"Attack":"Onde Boréale","LvL":0},
			{"Attack":"Ultrason","LvL":0},
			{"Attack":"Picanon","LvL":50},
		],
		"Evolution": null},
	"Fantominus": {
		"PV":30,
		"Attaque":35,
		"Defense":30,
		"AttaqueSpe":100,
		"DefenseSpe":35,
		"Vitesse":80,
		"Type1":"Spectre",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":1}],
		"EXP":95,
		"Courbe_EXP":"Parabolique",
		"Poids":0.1,
		"Taux_de_capture":190,
		"NativeAttacks":[
			{"Attack":"Léchouille","LvL":0},
			{"Attack":"Onde Folie","LvL":0},
			{"Attack":"Ombre Nocturne","LvL":0},
			{"Attack":"Hypnose","LvL":27},
			{"Attack":"Dévorêve","LvL":35}
		],
		"Evolution": {"Name":"Spectrum","LvL":25}},
	"Spectrum": {
		"PV":45,
		"Attaque":50,
		"Defense":45,
		"AttaqueSpe":115,
		"DefenseSpe":55,
		"Vitesse":95,
		"Type1":"Spectre",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":2}],
		"EXP":126,
		"Courbe_EXP":"Parabolique",
		"Poids":0.1,
		"Taux_de_capture":90,
		"NativeAttacks":[
			{"Attack":"Léchouille","LvL":0},
			{"Attack":"Onde Folie","LvL":0},
			{"Attack":"Ombre Nocturne","LvL":0},
			{"Attack":"Hypnose","LvL":29},
			{"Attack":"Dévorêve","LvL":38}
		],
		"Evolution": {"Name":"Ectoplasma","Autre":"Échange"}},
	"Ectoplasma": {
		"PV":60,
		"Attaque":65,
		"Defense":60,
		"AttaqueSpe":130,
		"DefenseSpe":75,
		"Vitesse":110,
		"Type1":"Spectre",
		"Type2":"Poison",
		"EV":[{"Stat":"AttaqueSpe","Value":3}],
		"EXP":190,
		"Courbe_EXP":"Parabolique",
		"Poids":40.5,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Léchouille","LvL":0},
			{"Attack":"Onde Folie","LvL":0},
			{"Attack":"Ombre Nocturne","LvL":0},
			{"Attack":"Hypnose","LvL":29},
			{"Attack":"Dévorêve","LvL":38}
		],
		"Evolution": null},
	"Onix": {
		"PV":35,
		"Attaque":45,
		"Defense":160,
		"AttaqueSpe":30,
		"DefenseSpe":45,
		"Vitesse":70,
		"Type1":"Roche",
		"Type2":"Sol",
		"EV":[{"Stat":"Defense","Value":1}],
		"EXP":108,
		"Courbe_EXP":"Moyenne",
		"Poids":210,
		"Taux_de_capture":45,
		"NativeAttacks":[
			{"Attack":"Charge","LvL":0},
			{"Attack":"Grincement","LvL":0},
			{"Attack":"Étreinte","LvL":15},
			{"Attack":"Jet-Pierres","LvL":19},
			{"Attack":"Frénésie","LvL":25},
			{"Attack":"Souplesse","LvL":33},
			{"Attack":"Armure","LvL":43}
		],
		"Evolution": null},
}

const NATURE = {#[Boost,Malus]
	"Assuré":["Defense","Attaque"],
	"Bizarre":["",""],
	"Brave":["Attaque","Vitesse"],
	"Calme":["DefenseSpe","Attaque"],
	"Discret":["AttaqueSpe","Vitesse"],
	"Docile":["",""],
	"Doux":["AttaqueSpe","Defense"],
	"Foufou":["AttaqueSpe","DefenseSpe"],
	"Gentil":["DefenseSpe","Defense"],
	"Hardi":["",""],
	"Jovial":["Vitesse","AttaqueSpe"],
	"Lâche":["Defense","DefenseSpe"],
	"Malin":["Defense","AttaqueSpe"],
	"Malpoli":["DefenseSpe","Vitesse"],
	"Mauvais":["Attaque","DefenseSpe"],
	"Modeste":["AttaqueSpe","Attaque"],
	"Naïf":["Vitesse","DefenseSpe"],
	"Pressé":["Vitesse","Defense"],
	"Prudent":["DefenseSpe","AttaqueSpe"],
	"Pudique":["",""],
	"Relax":["Defense","Vitesse"],
	"Rigide":["Attaque","AttaqueSpe"],
	"Sérieux":["",""],
	"Solo":["Attaque","Defense"],
	"Timide":["Vitesse","Attaque"]
}

const ATTACKS = {
	"Statut_Confus":{
		"PP":null,
		"Type":"Normal",
		"Puissance":40,
		"Precision":null,
		"Priorite":null,
		"Critique":null,
		"Categorie":"Physique"},
	"Lutte": {
		"PP":null,
		"Type":"Normal",
		"Puissance":50,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Charge": {
		"PP":35,
		"Type":"Normal",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Rugissement": {
		"PP":40,
		"Type":"Normal",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Vampigraine": {
		"PP":10,
		"Type":"Plante",
		"Puissance":null,
		"Precision":90,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Fouet Lianes": {
		"PP":25,
		"Type":"Plante",
		"Puissance":45,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Poudre Toxik": {
		"PP":35,
		"Type":"Poison",
		"Puissance":null,
		"Precision":75,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Tranch'Herbe": {
		"PP":25,
		"Type":"Plante",
		"Puissance":55,
		"Precision":95,
		"Priorite":0,
		"Critique":2,
		"Categorie":"Physique"},
	"Croissance": {
		"PP":20,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Poudre Dodo": {
		"PP":15,
		"Type":"Plante",
		"Puissance":null,
		"Precision":75,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Lance Soleil": {
		"PP":10,
		"Type":"Plante",
		"Puissance":120,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Griffe": {
		"PP":35,
		"Type":"Normal",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Flammèche": {
		"PP":25,
		"Type":"Feu",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Groz'Yeux": {
		"PP":30,
		"Type":"Normal",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Frénésie": {
		"PP":20,
		"Type":"Normal",
		"Puissance":20,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Tranche": {
		"PP":20,
		"Type":"Normal",
		"Puissance":70,
		"Precision":100,
		"Priorite":0,
		"Critique":2,
		"Categorie":"Physique"},
	"Lance-Flammes": {
		"PP":15,
		"Type":"Feu",
		"Puissance":90,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Danse-Flammes": {
		"PP":15,
		"Type":"Feu",
		"Puissance":35,
		"Precision":85,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Mimi-Queue": {
		"PP":30,
		"Type":"Normal",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Écume": {
		"PP":30,
		"Type":"Eau",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Pistolet à O": {
		"PP":25,
		"Type":"Eau",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Repli": {
		"PP":40,
		"Type":"Eau",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Morsure": {
		"PP":25,
		"Type":"Normal",
		"Puissance":60,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Coud'Krâne": {
		"PP":10,
		"Type":"Normal",
		"Puissance":130,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Hydrocanon": {
		"PP":5,
		"Type":"Eau",
		"Puissance":110,
		"Precision":80,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Sécrétion": {
		"PP":40,
		"Type":"Insecte",
		"Puissance":null,
		"Precision":95,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Armure": {
		"PP":30,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Choc Mental": {
		"PP":25,
		"Type":"Psy",
		"Puissance":50,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Para-Spore": {
		"PP":30,
		"Type":"Plante",
		"Puissance":null,
		"Precision":75,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Ultrason": {
		"PP":20,
		"Type":"Normal",
		"Puissance":null,
		"Precision":55,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Cyclone": {
		"PP":20,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":-6,
		"Critique":1,
		"Categorie":"Statut"},
	"Tornade": {
		"PP":35,
		"Type":"Vol",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Rafale Psy": {
		"PP":20,
		"Type":"Psy",
		"Puissance":65,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Dard-Venin": {
		"PP":35,
		"Type":"Poison",
		"Puissance":15,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Furie": {
		"PP":20,
		"Type":"Normal",
		"Puissance":15,
		"Precision":85,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Puissance": {
		"PP":30,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Double-Dard": {
		"PP":20,
		"Type":"Insecte",
		"Puissance":25,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Dard-Nuée": {
		"PP":20,
		"Type":"Insecte",
		"Puissance":25,
		"Precision":95,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Hâte": {
		"PP":30,
		"Type":"Psy",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Jet de Sable": {
		"PP":15,
		"Type":"Sol",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Vive-Attaque": {
		"PP":30,
		"Type":"Normal",
		"Puissance":40,
		"Precision":100,
		"Priorite":1,
		"Critique":1,
		"Categorie":"Physique"},
	"Cru-Aile": {
		"PP":35,
		"Type":"Vol",
		"Puissance":60,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Mimique": {
		"PP":20,
		"Type":"Vol",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Croc de Mort": {
		"PP":15,
		"Type":"Normal",
		"Puissance":80,
		"Precision":90,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Croc Fatal": {
		"PP":10,
		"Type":"Normal",
		"Puissance":null,
		"Precision":90,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Picpic": {
		"PP":35,
		"Type":"Vol",
		"Puissance":35,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Bec Vrille": {
		"PP":20,
		"Type":"Vol",
		"Puissance":80,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Ligotage": {
		"PP":20,
		"Type":"Normal",
		"Puissance":15,
		"Precision":90,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Regard Médusant": {
		"PP":30,
		"Type":"Normal",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Grincement": {
		"PP":40,
		"Type":"Normal",
		"Puissance":null,
		"Precision":85,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Acide": {
		"PP":30,
		"Type":"Poison",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Éclair": {
		"PP":30,
		"Type":"Électrik",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Cage-Éclair": {
		"PP":20,
		"Type":"Électrik",
		"Puissance":null,
		"Precision":90,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Reflet": {
		"PP":15,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Souplesse": {
		"PP":20,
		"Type":"Normal",
		"Puissance":80,
		"Precision":75,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Météores": {
		"PP":20,
		"Type":"Normal",
		"Puissance":60,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Tonnerre": {
		"PP":15,
		"Type":"Électrik",
		"Puissance":90,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Fatal-Foudre": {
		"PP":10,
		"Type":"Électrik",
		"Puissance":110,
		"Precision":70,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Mur Lumière": {
		"PP":30,
		"Type":"Psy",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Combo-Griffe": {
		"PP":15,
		"Type":"Normal",
		"Puissance":18,
		"Precision":80,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Double Pied": {
		"PP":30,
		"Type":"Combat",
		"Puissance":30,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Plaquage": {
		"PP":15,
		"Type":"Normal",
		"Puissance":85,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Koud'Korne": {
		"PP":25,
		"Type":"Normal",
		"Puissance":65,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Empal'Korne": {
		"PP":5,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Mania": {
		"PP":10,
		"Type":"Normal",
		"Puissance":120,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Écras'Face": {
		"PP":35,
		"Type":"Normal",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Berceuse": {
		"PP":15,
		"Type":"Normal",
		"Puissance":null,
		"Precision":55,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Torgnoles": {
		"PP":10,
		"Type":"Normal",
		"Puissance":15,
		"Precision":85,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Lilliput": {
		"PP":10,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Métronome": {
		"PP":10,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Boul'Armure": {
		"PP":40,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Hurlement": {
		"PP":20,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":-6,
		"Critique":1,
		"Categorie":"Statut"},
	"Onde Folie": {
		"PP":10,
		"Type":"Spectre",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Entrave": {
		"PP":20,
		"Type":"Normal",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Repos": {
		"PP":5,
		"Type":"Psy",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Damoclès": {
		"PP":15,
		"Type":"Normal",
		"Puissance":120,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Vampirisme": {
		"PP":10,
		"Type":"Insecte",
		"Puissance":80,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Buée Noire": {
		"PP":30,
		"Type":"Glace",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Vol-Vie": {
		"PP":25,
		"Type":"Plante",
		"Puissance":20,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Danse-Fleur": {
		"PP":10,
		"Type":"Plante",
		"Puissance":120,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Spore": {
		"PP":15,
		"Type":"Plante",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Psyko": {
		"PP":10,
		"Type":"Psy",
		"Puissance":90,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Tunnel": {
		"PP":10,
		"Type":"Sol",
		"Puissance":80,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Séisme": {
		"PP":10,
		"Type":"Sol",
		"Puissance":100,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Jackpot": {
		"PP":20,
		"Type":"Normal",
		"Puissance":40,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Balayage": {
		"PP":20,
		"Type":"Combat",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Poing-Karaté": {
		"PP":25,
		"Type":"Combat",
		"Puissance":50,
		"Precision":100,
		"Priorite":0,
		"Critique":2,
		"Categorie":"Physique"},
	"Frappe Atlas": {
		"PP":20,
		"Type":"Combat",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Bélier": {
		"PP":20,
		"Type":"Normal",
		"Puissance":90,
		"Precision":85,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Hypnose": {
		"PP":20,
		"Type":"Psy",
		"Puissance":null,
		"Precision":60,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Amnésie": {
		"PP":20,
		"Type":"Psy",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Téléport": {
		"PP":20,
		"Type":"Psy",
		"Puissance":null,
		"Precision":null,
		"Priorite":-6,
		"Critique":1,
		"Categorie":"Statut"},
	"Télékinésie": {
		"PP":15,
		"Type":"Psy",
		"Puissance":null,
		"Precision":80,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Soin": {
		"PP":5,
		"Type":"Normal",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Protection": {
		"PP":20,
		"Type":"Psy",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Sacrifice": {
		"PP":20,
		"Type":"Combat",
		"Puissance":80,
		"Precision":80,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Constriction": {
		"PP":35,
		"Type":"Normal",
		"Puissance":10,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Bouclier": {
		"PP":20,
		"Type":"Psy",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Jet-Pierres": {
		"PP":15,
		"Type":"Roche",
		"Puissance":50,
		"Precision":90,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Destruction": {
		"PP":5,
		"Type":"Normal",
		"Puissance":200,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Explosion": {
		"PP":5,
		"Type":"Normal",
		"Puissance":250,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Écrasement": {
		"PP":20,
		"Type":"Normal",
		"Puissance":65,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Coup d'Boule": {
		"PP":15,
		"Type":"Normal",
		"Puissance":70,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Sonicboom": {
		"PP":20,
		"Type":"Normal",
		"Puissance":null,
		"Precision":90,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Danse-Lames": {
		"PP":20,
		"Type":"Normal",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Triplattaque": {
		"PP":10,
		"Type":"Normal",
		"Puissance":80,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Onde Boréale": {
		"PP":20,
		"Type":"Glace",
		"Puissance":65,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Laser Glace": {
		"PP":10,
		"Type":"Glace",
		"Puissance":90,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Gaz Toxik": {
		"PP":40,
		"Type":"Poison",
		"Puissance":null,
		"Precision":90,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Détritus": {
		"PP":20,
		"Type":"Poison",
		"Puissance":65,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Acidarmure": {
		"PP":20,
		"Type":"Poison",
		"Puissance":null,
		"Precision":null,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Statut"},
	"Claquoir": {
		"PP":15,
		"Type":"Eau",
		"Puissance":35,
		"Precision":85,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Picanon": {
		"PP":15,
		"Type":"Normal",
		"Puissance":20,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Léchouille": {
		"PP":30,
		"Type":"Spectre",
		"Puissance":30,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
	"Ombre Nocturne": {
		"PP":15,
		"Type":"Spectre",
		"Puissance":null,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Dévorêve": {
		"PP":15,
		"Type":"Psy",
		"Puissance":100,
		"Precision":100,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Special"},
	"Étreinte": {
		"PP":20,
		"Type":"Normal",
		"Puissance":15,
		"Precision":85,
		"Priorite":0,
		"Critique":1,
		"Categorie":"Physique"},
}

const TYPE_COLOR = {
	"Normal": Color8(162,162,162),
	"Feu": Color8(252,28,29),
	"Eau": Color8(20,132,255),
	"Plante": Color8(45,169,16),
	"Électrik": Color8(255,193,0),
	"Glace": Color8(26,224,253),
	"Combat": Color8(255,125,3),
	"Poison": Color8(158,58,236),
	"Sol": Color8(161,77,19),
	"Vol": Color8(117,185,255),
	"Psy": Color8(255,56,125),
	"Insecte": Color8(144,166,2),
	"Roche": Color8(178,169,118),
	"Spectre": Color8(121,61,122),
	"Dragon": Color8(75,97,255)
}

const CRIT_OCCUR = {
	1 : 1/24.0,
	2 : 1/8.0,
	3 : 1/2.0,
	4 : 1,
	5 : 1
}

const MODIF_STAT = {
	6 : 4.0,
	5 : 7/2.0,
	4 : 3.0,
	3 : 5/2.0,
	2 : 2.0,
	1 : 3/2.0,
	0 : 1.0,
	-1 : 2/3.0,
	-2 : 1/2.0,
	-3 : 2/5.0,
	-4 : 1/3.0,
	-5 : 2/7.0,
	-6 : 1/4.0
}

const MODIF_PRE = {
	6 : 3.0,
	5 : 8/3.0,
	4 : 7/3.0,
	3 : 2.0,
	2 : 5/3.0,
	1 : 4/3.0,
	0 : 1.0,
	-1 : 3/4.0,
	-2 : 3/5.0,
	-3 : 1/2.0,
	-4 : 3/7.0,
	-5 : 3/8.0,
	-6 : 1/3.0
}

const TABLE_TYPE = {
	"Normal" : {
		"Roche" : 0.5,
		"Spectre" : 0
	},
	"Feu" : {
		"Feu" : 0.5,
		"Eau" : 0.5,
		"Plante" : 2,
		"Glace" : 2,
		"Insecte" : 2,
		"Roche" : 0.5,
		"Dragon" : 0.5
	},
	"Eau" : {
		"Feu" : 2,
		"Eau" : 0.5,
		"Plante" : 0.5,
		"Sol" : 2,
		"Roche" : 2,
		"Dragon" : 0.5
	},
	"Plante" : {
		"Feu" : 0.5,
		"Eau" : 2,
		"Plante" : 0.5,
		"Poison" : 0.5,
		"Sol" : 2,
		"Vol" : 0.5,
		"Insecte" : 0.5,
		"Roche" : 2,
		"Dragon" : 0.5
	},
	"Électrik" : {
		"Eau" : 2,
		"Plante" : 0.5,
		"Électrik" : 0.5,
		"Sol" : 0,
		"Vol" : 2,
		"Dragon" : 0.5
	},
	"Glace" : {
		"Eau" : 0.5,
		"Plante" : 2,
		"Glace" : 0.5,
		"Sol" : 2,
		"Vol" : 2,
		"Dragon" : 2
	},
	"Combat" : {
		"Normal" : 2,
		"Glace" : 2,
		"Poison" : 0.5,
		"Vol" : 0.5,
		"Psy" : 0.5,
		"Insecte" : 0.5,
		"Roche" : 2,
		"Spectre" : 0
	},
	"Poison" : {
		"Plante" : 2,
		"Poison" : 0.5,
		"Sol" : 0.5,
		"Insecte" : 2,
		"Roche" : 0.5,
		"Spectre" : 0.5
	},
	"Sol" : {
		"Feu" : 2,
		"Plante" : 0.5,
		"Électrik" : 2,
		"Poison" : 2,
		"Vol" : 0,
		"Insecte" : 0.5,
		"Roche" : 2
	},
	"Vol" : {
		"Plante" : 2,
		"Électrik" : 0.5,
		"Combat" : 2,
		"Insecte" : 2,
		"Roche" : 0.5
	},
	"Psy" : {
		"Combat" : 2,
		"Poison" : 2,
		"Psy" : 0.5
	},
	"Insecte" : {
		"Feu" : 0.5,
		"Plante" : 2,
		"Combat" : 0.5,
		"Poison" : 2,
		"Vol" : 0.5,
		"Psy" : 2,
		"Spectre" : 0.5
	},
	"Roche" : {
		"Feu" : 2,
		"Glace" : 2,
		"Combat" : 0.5,
		"Sol" : 0.5,
		"Vol" : 2,
		"Insecte" : 2
	},
	"Spectre" : {
		"Normal" : 0,
		"Psy" : 0,
		"Spectre" : 2
	},
	"Dragon" : {
		"Dragon" : 2
	}
}
